apiVersion: v1
kind: Service
metadata:
  name: watchdog-service
  namespace: watchdog-ns
spec:
  selector:
    app: watchdog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
