name: Docker K8s Setup
on:
  push:
    branches: [ "feature/k8s-setup" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64, linux/arm64
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKER_IMAGE_NAME }}:latest
          ${{ vars.DOCKER_IMAGE_NAME }}:v1
